---
title: "HW4"
author: "Jingting Gao"
date: "9/29/2016"
output: html_document
---

```{r}
#1
#a)
c(1:20)#combine values into a vector
#b)
c(20:1)#combine values into a vector
#c)
c(1:20,19:1)#combine values into a vector
#d)
tmp<-c(4,6,3)#assign a vector with name
tmp
#e)
rep(tmp,10)#repeat the vector tmp 10 times
#f)
rep(tmp,l=31)#repeat the vector tmp with length 31
#g)
rep(tmp,times=c(10,20,30))#repeat each element in the vector tmp with respected times in times vector
```
```{r}
#2
x<-seq(3,6,by=0.1)#set the domain of x from 3 to 6 increase by 0.1
exp(x)*cos(x)#construct a function respect to x
```
```{r}
#3
#a)
i<-seq(3,36,by=3)#set i as a sequence from 3 to 36 with increment of 3
j<-seq(1,34,by=3)#set j as a sequence from 1 to 34 with increment of 3
(0.1^i)*(0.2^j)#get vector with common function respect to defined i and j
#b)
i<-seq(1,25)
(2^i)/i#get vector with common function respect to defined i
```
```{r}
#4
#a)
i<-(10:100)#set the domain of i from 10 to 100
sum(i^3+4*i^2)#get the sum of function respect to i
#b)
i<-(1:25)#set the domain of i from 1 to 25
sum((2^i)/i+(3^i)/(i^2))#get the sum of function respect to i
```
```{r}
#5
#a)
paste("label",1:30,sep=" ")#use function paste to paste label from 1 to 30
#b)
paste("fn",1:30,sep="")#use function paste to paste fn from 1 to 30 without seperator
```
```{r}
#6
set.seed(50)
xVec <- sample(0:999, 250, replace=T) 
yVec <- sample(0:999, 250, replace=T)
#a)
yVec[-1]-xVec[-250]#each element in yVec except the fisrt one substract respect
#b)
sin(yVec[-250])/cos(xVec[-1])#sin of yVec from y1-y249 divided cos of xVex from x2 to x250
#c)
xVec[-c(249,250)] + 2*xVec[-c(1,250)]-xVec[-c(1,2)]#get x(i-2) from x1 to x248, x(i-1) from x2 to x249, and xi from x3 to x250
#d)
sum(exp(-xVec[-1])/(xVec[-250]+10))#get the sum of common function with respected x(i+1) from x2 to x250 and xi from x1 to x249
```
```{r}
#7
#a)
yVec[yVec>600]#list all elements in yVec that greater than 600
#b)
which(yVec>600)#get the index of the element in yVec which are greater than 600
#c)
xVec[which(yVec>600)]#get the elements in xVec with same index position in b)
#d)
sqrt(abs(xVec-mean(xVec)))#use sqrt, abs, mean function to get the vector
#e)
sum(yVec>max(yVec)-200)#get the number of elements in yVec that within 200 of the maximum value in yVec
#f)
sum(xVec%%2==0)#get the number of elements in xVec that divide 2 with reminder 0
#g)
xVec[order(yVec)]#use order function to sort xVec with the order of increasing values in yVec
#h)
yVec[c(T,F,F)]#set each elements in yVec in the sequence of True False False, repeatedly, and we get the first True with every 3 elements
```
```{r}
#8
1+sum(cumprod(seq(2,38,by=2)/seq(3,39,by=2)))#apply cumprod to each sequence, and get the sum
```


